use std::collections::BTreeMap;
use std::path::Path;

use crate::error::VaultError;
use crate::store::Vault;

/// Supported output formats for env generation.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum EnvFormat {
    Dotenv,
    Json,
    Yaml,
    Toml,
    Shell,
}

/// Detected frameworks and their env prefix conventions.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum Framework {
    NextJs,
    Vite,
    Remix,
    Astro,
    SvelteKit,
    Nuxt,
    Unknown,
}

impl Framework {
    /// Detect the framework from the project directory.
    pub fn detect(project_dir: &Path) -> Self {
        if project_dir.join("next.config.js").exists()
            || project_dir.join("next.config.ts").exists()
            || project_dir.join("next.config.mjs").exists()
        {
            return Self::NextJs;
        }
        if project_dir.join("vite.config.ts").exists()
            || project_dir.join("vite.config.js").exists()
        {
            return Self::Vite;
        }
        if project_dir.join("remix.config.js").exists()
            || project_dir.join("remix.config.ts").exists()
        {
            return Self::Remix;
        }
        if project_dir.join("astro.config.mjs").exists()
            || project_dir.join("astro.config.ts").exists()
        {
            return Self::Astro;
        }
        if project_dir.join("svelte.config.js").exists() {
            return Self::SvelteKit;
        }
        if project_dir.join("nuxt.config.ts").exists()
            || project_dir.join("nuxt.config.js").exists()
        {
            return Self::Nuxt;
        }
        Self::Unknown
    }

    /// Get the public env var prefix for this framework.
    pub fn public_prefix(&self) -> Option<&'static str> {
        match self {
            Self::NextJs => Some("NEXT_PUBLIC_"),
            Self::Vite => Some("VITE_"),
            Self::Remix => None, // Remix uses loader functions
            Self::Astro => Some("PUBLIC_"),
            Self::SvelteKit => Some("PUBLIC_"),
            Self::Nuxt => Some("NUXT_PUBLIC_"),
            Self::Unknown => None,
        }
    }
}

/// Environment variable generator.
pub struct EnvGenerator<'a> {
    vault: &'a Vault,
    framework: Framework,
}

impl<'a> EnvGenerator<'a> {
    pub fn new(vault: &'a Vault, framework: Framework) -> Self {
        Self { vault, framework }
    }

    /// Auto-detect framework from project dir.
    pub fn with_detection(vault: &'a Vault, project_dir: &Path) -> Self {
        Self {
            vault,
            framework: Framework::detect(project_dir),
        }
    }

    /// Collect all credential values as env var mappings.
    pub fn collect_vars(&self) -> Result<BTreeMap<String, EnvVar>, VaultError> {
        let mut vars = BTreeMap::new();

        for key in self.vault.list() {
            let entry = self.vault.get(key)?;
            let source = format!(
                "{} ({})",
                entry.offering_id, entry.resource_id
            );

            for (cred_key, cred_value) in &entry.credentials {
                let env_name = credential_to_env_name(&entry.offering_id, cred_key);
                vars.insert(
                    env_name,
                    EnvVar {
                        value: cred_value.clone(),
                        source: source.clone(),
                        is_public: false,
                    },
                );
            }
        }

        Ok(vars)
    }

    /// Generate env file content in the specified format.
    pub fn generate(&self, format: EnvFormat) -> Result<String, VaultError> {
        let vars = self.collect_vars()?;

        match format {
            EnvFormat::Dotenv => Ok(self.generate_dotenv(&vars)),
            EnvFormat::Json => self.generate_json(&vars),
            EnvFormat::Yaml => Ok(self.generate_yaml(&vars)),
            EnvFormat::Toml => Ok(self.generate_toml(&vars)),
            EnvFormat::Shell => Ok(self.generate_shell(&vars)),
        }
    }

    fn generate_dotenv(&self, vars: &BTreeMap<String, EnvVar>) -> String {
        let mut lines = Vec::new();
        lines.push(format!(
            "# Generated by OSP — framework: {:?}",
            self.framework
        ));
        lines.push(String::new());

        let mut current_source = String::new();
        for (name, var) in vars {
            if var.source != current_source {
                if !current_source.is_empty() {
                    lines.push(String::new());
                }
                lines.push(format!("# {}", var.source));
                current_source = var.source.clone();
            }
            lines.push(format!("{}=\"{}\"", name, escape_dotenv_value(&var.value)));
        }
        lines.push(String::new());
        lines.join("\n")
    }

    fn generate_json(&self, vars: &BTreeMap<String, EnvVar>) -> Result<String, VaultError> {
        let map: BTreeMap<&str, &str> = vars.iter().map(|(k, v)| (k.as_str(), v.value.as_str())).collect();
        serde_json::to_string_pretty(&map).map_err(VaultError::from)
    }

    fn generate_yaml(&self, vars: &BTreeMap<String, EnvVar>) -> String {
        let mut lines = Vec::new();
        lines.push("# Generated by OSP".to_string());
        for (name, var) in vars {
            lines.push(format!("{}: \"{}\"", name, var.value.replace('"', "\\\"")));
        }
        lines.join("\n")
    }

    fn generate_toml(&self, vars: &BTreeMap<String, EnvVar>) -> String {
        let mut lines = Vec::new();
        lines.push("# Generated by OSP".to_string());
        lines.push("[env]".to_string());
        for (name, var) in vars {
            lines.push(format!("{} = \"{}\"", name, var.value.replace('"', "\\\"")));
        }
        lines.join("\n")
    }

    fn generate_shell(&self, vars: &BTreeMap<String, EnvVar>) -> String {
        let mut lines = Vec::new();
        lines.push("#!/bin/sh".to_string());
        lines.push("# Generated by OSP".to_string());
        for (name, var) in vars {
            lines.push(format!(
                "export {}='{}'",
                name,
                var.value.replace('\'', "'\\''")
            ));
        }
        lines.join("\n")
    }
}

/// A generated env var with metadata.
#[derive(Debug, Clone)]
pub struct EnvVar {
    pub value: String,
    pub source: String,
    pub is_public: bool,
}

/// Convert an offering_id + credential key to an env var name.
///
/// Example: "supabase/managed-postgres" + "connection_uri" -> "SUPABASE_MANAGED_POSTGRES_CONNECTION_URI"
fn credential_to_env_name(offering_id: &str, credential_key: &str) -> String {
    let prefix = offering_id
        .replace('/', "_")
        .replace('-', "_")
        .to_uppercase();
    let suffix = credential_key.to_uppercase();
    format!("{prefix}_{suffix}")
}

fn escape_dotenv_value(value: &str) -> String {
    value.replace('\\', "\\\\").replace('"', "\\\"")
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn credential_to_env_name_basic() {
        assert_eq!(
            credential_to_env_name("supabase/managed-postgres", "connection_uri"),
            "SUPABASE_MANAGED_POSTGRES_CONNECTION_URI"
        );
    }

    #[test]
    fn credential_to_env_name_simple() {
        assert_eq!(
            credential_to_env_name("resend/email", "api_key"),
            "RESEND_EMAIL_API_KEY"
        );
    }

    #[test]
    fn framework_detect_unknown() {
        let dir = tempfile::tempdir().unwrap();
        assert_eq!(Framework::detect(dir.path()), Framework::Unknown);
    }

    #[test]
    fn framework_public_prefix() {
        assert_eq!(Framework::NextJs.public_prefix(), Some("NEXT_PUBLIC_"));
        assert_eq!(Framework::Vite.public_prefix(), Some("VITE_"));
        assert_eq!(Framework::Unknown.public_prefix(), None);
    }
}
